### PR TITLE
PNDA-2282: Pass more specific reason back in case of bad health for deployment manager

### PR DESCRIPTION
**Pull request by GaneshManal**
# Problem Statement:
PNDA-2282: Pass more specific reason back in case of bad health for deployment manager

# Analysis:
The exception handling for deployment manager APIs not reachable is done at very broad level.
It simply says - api's not working if api call doesn't give response.

# Change:
Done the exception handling for handling the exceptions raised by deployment manager and show the appropriate cause message in health matrix.

# Test details:
Verified the fix for AWS:
UBUNTU - PICO -CDH & HDP
UBUNTU - STD -CDH & HDP
RHEL - PICO -CDH & HDP
RHEL - STD -CDH & HDP
Verification pending for OpenStack

### CODE REVIEW

**Comment by trsmith2** [comment]
This is a good step in the right direction and I like the related change to the console which links the logs for the deployment manager to this component - this is useful.

However, the errors are still unclear and badly formatted. 

This is an example of what I see if I kill the package server along with some other components - 

image

This is an example of what another component looks like - 

image

There are other more minor code quality issues, but let's address the main issue first and then I'll give more specific pointers.

**Comment by GaneshManal** [comment]
Trevor, on stopping the hbase service, seeing the below error ( cause message is polished to show actual human readable message and not the json )

abc

Still not able to simulate the unsorted list of cause messages, like in snap you attached.
Was it result of only stopping the hbase service ?

**Comment by trsmith2** [comment]
Yes, but any problem on any service is formatted in the same way

**Comment by GaneshManal** [comment]
abc

So, is this appropriate & readable ? or we need more formatting ?

**Comment by trsmith2** [comment]
It's an improvement, this PR is closed and the branch is deleted though, do you have another PR?

**Comment by GaneshManal** [comment]
Created a new PR - https://github.com/pndaproject/platform-testing/pull/46

**Pull request closed without merging**
